[2023-04-16T11:28:43.750+0700] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: python_dag_v2.greet manual__2023-04-16T04:28:41.935567+00:00 [queued]>
[2023-04-16T11:28:43.754+0700] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: python_dag_v2.greet manual__2023-04-16T04:28:41.935567+00:00 [queued]>
[2023-04-16T11:28:43.754+0700] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T11:28:43.754+0700] {taskinstance.py:1289} INFO - Starting attempt 1 of 6
[2023-04-16T11:28:43.754+0700] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-16T11:28:43.770+0700] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): greet> on 2023-04-16 04:28:41.935567+00:00
[2023-04-16T11:28:43.772+0700] {standard_task_runner.py:55} INFO - Started process 16879 to run task
[2023-04-16T11:28:43.775+0700] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'python_dag_v2', 'greet', 'manual__2023-04-16T04:28:41.935567+00:00', '--job-id', '230', '--raw', '--subdir', 'DAGS_FOLDER/dag_python_operator.py', '--cfg-path', '/tmp/tmpbeb2mnq9']
[2023-04-16T11:28:43.777+0700] {standard_task_runner.py:83} INFO - Job 230: Subtask greet
[2023-04-16T11:28:43.807+0700] {task_command.py:389} INFO - Running <TaskInstance: python_dag_v2.greet manual__2023-04-16T04:28:41.935567+00:00 [running]> on host ahyar-Aspire-A514-54
[2023-04-16T11:28:43.849+0700] {taskinstance.py:1516} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ahyar
AIRFLOW_CTX_DAG_ID=python_dag_v2
AIRFLOW_CTX_TASK_ID=greet
AIRFLOW_CTX_EXECUTION_DATE=2023-04-16T04:28:41.935567+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-16T04:28:41.935567+00:00
[2023-04-16T11:28:43.850+0700] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/ahyar/Documents/tut_folder/tut_python/python_script/tut_airflow/env_airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/ahyar/Documents/tut_folder/tut_python/python_script/tut_airflow/env_airflow/lib/python3.9/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/ahyar/Documents/tut_folder/tut_python/python_script/tut_airflow/dags/dag_python_operator.py", line 13, in greet
    print(f"Hello world from {project} {language}")
NameError: name 'project' is not defined
[2023-04-16T11:28:43.852+0700] {taskinstance.py:1327} INFO - Marking task as UP_FOR_RETRY. dag_id=python_dag_v2, task_id=greet, execution_date=20230416T042841, start_date=20230416T042843, end_date=20230416T042843
[2023-04-16T11:28:43.863+0700] {standard_task_runner.py:100} ERROR - Failed to execute job 230 for task greet (name 'project' is not defined; 16879)
[2023-04-16T11:28:43.867+0700] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-16T11:28:43.876+0700] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
